# Generated by Django 3.1.7 on 2021-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
