# Generated by Django 3.1.7 on 2021-12-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211231_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_status',
        ),
        migrations.AddField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
