# Generated by Django 3.1.7 on 2021-12-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211231_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student_status'),
        ),
    ]
