# Generated by Django 3.1.7 on 2021-12-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211231_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'management'), (2, 'staff'), (3, 'finance')], default=1, max_length=10),
        ),
    ]
