# Generated by Django 4.0 on 2022-01-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_settings_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='dueDate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='uniqueId',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('cash', 'cash'), ('transfer', 'transfer')], default='cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('TUTION', 'TUTION'), ('APPLICATION', 'APPLICATION'), ('ACCEPTANCE', 'ACCEPTANCE'), ('OTHERS', 'OTHERS')], default='TUTION', max_length=100),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.invoice'),
        ),
    ]
