# Generated by Django 4.0 on 2022-01-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_invoicedetail_delete_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
