# Generated by Django 4.0 on 2022-01-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_sop_sopdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='customer_points',
            field=models.IntegerField(default=0),
        ),
    ]
