# Generated by Django 4.0 on 2022-01-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_staffs_customer_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('one', models.CharField(blank=True, max_length=255, null=True)),
                ('amountOne', models.CharField(blank=True, max_length=255, null=True)),
                ('two', models.CharField(blank=True, max_length=255, null=True)),
                ('amountTwo', models.CharField(blank=True, max_length=255, null=True)),
                ('three', models.CharField(blank=True, max_length=255, null=True)),
                ('amountThree', models.CharField(blank=True, max_length=255, null=True)),
                ('four', models.CharField(blank=True, max_length=255, null=True)),
                ('amountFour', models.CharField(blank=True, max_length=255, null=True)),
                ('five', models.CharField(blank=True, max_length=255, null=True)),
                ('amountFive', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
