# Generated by Django 4.0 on 2022-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('TUTION', 'TUTION'), ('APPLICATION', 'APPLICATION'), ('ACCEPTANCE', 'ACCEPTANCE'), ('OTHERS', 'OTHERS')], default='TUTION', max_length=100)),
                ('type', models.CharField(choices=[('cash', 'cash'), ('transfer', 'transfer')], default='cash', max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentTerms', models.CharField(choices=[('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='14 days', max_length=100)),
                ('total', models.FloatField(default=0)),
            ],
        ),
    ]
