# Generated by Django 4.0 on 2022-01-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_reciept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='paymentTerms',
        ),
        migrations.RemoveField(
            model_name='reciept',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reciept',
            name='type',
        ),
        migrations.AddField(
            model_name='reciept',
            name='acceptance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciept',
            name='application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciept',
            name='others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciept',
            name='tution',
            field=models.BooleanField(default=False),
        ),
    ]
