# Generated by Django 4.0 on 2022-01-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_programme_students_student_id_students_totalfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='ip_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='nin',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
