# Generated by Django 4.0 on 2022-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_students_ip_id_students_nin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymenttype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ptype_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
