# Generated by Django 4.0 on 2022-01-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='ptype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
