# Generated by Django 4.0 on 2022-01-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_reciept_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='balace',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reciept',
            name='stu_programme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reciept',
            name='student_nin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='ptype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paymenttype'),
        ),
    ]
