# Generated by Django 4.0 on 2022-01-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_reciept_balace_reciept_stu_programme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciept',
            old_name='balace',
            new_name='balance',
        ),
    ]
