# Generated by Django 4.0 on 2022-01-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_balace_reciept_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cons',
            name='comment',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
