# Generated by Django 4.0 on 2022-01-09 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_feetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffDepartments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='customer_points',
        ),
        migrations.AddField(
            model_name='staffs',
            name='ip_id_staff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='sf_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staffdepartments'),
        ),
    ]
